use std::fmt::Write;

use oa_forge_ir::*;

/// Emit Valibot schemas from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;

    let mut used = UsedFunctions::default();
    let mut body = String::new();

    for typedef in api.types.values() {
        emit_schema_def(typedef, &mut body, &mut used)?;
        writeln!(body)?;
    }

    for endpoint in &api.endpoints {
        emit_endpoint_schemas(endpoint, &mut body, &mut used)?;
    }

    let imports: Vec<&str> = used.collect();
    writeln!(
        out,
        "import {{ type InferOutput, {} }} from 'valibot';",
        imports.join(", ")
    )?;
    writeln!(out)?;

    out.push_str(&body);
    Ok(())
}

#[derive(Default)]
struct UsedFunctions {
    fns: std::collections::BTreeSet<&'static str>,
}

impl UsedFunctions {
    fn mark(&mut self, name: &'static str) {
        self.fns.insert(name);
    }

    fn collect(&self) -> Vec<&str> {
        self.fns.iter().copied().collect()
    }
}

fn emit_schema_def(
    typedef: &TypeDef,
    out: &mut String,
    used: &mut UsedFunctions,
) -> Result<(), std::fmt::Error> {
    let base = type_repr_to_valibot(&typedef.repr, used);
    let with_format = append_format(&base, typedef.format.as_deref(), used);
    let schema = append_constraints(&with_format, &typedef.constraints, used);

    match &typedef.repr {
        TypeRepr::Ref { name } => {
            used.mark("lazy");
            writeln!(out, "export const {name}Schema = lazy(() => {name}Schema);")?;
        }
        _ => {
            writeln!(out, "export const {}Schema = {schema};", typedef.name)?;
        }
    }

    writeln!(
        out,
        "export type {} = InferOutput<typeof {}Schema>;",
        typedef.name, typedef.name
    )?;

    Ok(())
}

/// Emit a Valibot object schema for params at the given location.
/// When `use_optional` is true, non-required params get `optional()` wrapping.
fn emit_params_schema(
    id: &str,
    suffix: &str,
    location: ParamLocation,
    use_optional: bool,
    endpoint: &Endpoint,
    out: &mut String,
    used: &mut UsedFunctions,
) -> Result<(), std::fmt::Error> {
    let params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == location)
        .collect();

    if params.is_empty() {
        return Ok(());
    }

    used.mark("object");
    write!(out, "export const {id}{suffix}Schema = object({{")?;
    for p in &params {
        let schema = type_repr_to_valibot(&p.repr, used);
        if use_optional && !p.required {
            used.mark("optional");
            write!(out, " {}: optional({schema}),", p.name)?;
        } else {
            write!(out, " {}: {schema},", p.name)?;
        }
    }
    writeln!(out, " }});")?;
    writeln!(out)?;
    Ok(())
}

fn emit_endpoint_schemas(
    endpoint: &Endpoint,
    out: &mut String,
    used: &mut UsedFunctions,
) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;

    emit_params_schema(
        id,
        "PathParams",
        ParamLocation::Path,
        false,
        endpoint,
        out,
        used,
    )?;
    emit_params_schema(
        id,
        "QueryParams",
        ParamLocation::Query,
        true,
        endpoint,
        out,
        used,
    )?;
    emit_params_schema(
        id,
        "HeaderParams",
        ParamLocation::Header,
        true,
        endpoint,
        out,
        used,
    )?;
    emit_params_schema(
        id,
        "CookieParams",
        ParamLocation::Cookie,
        true,
        endpoint,
        out,
        used,
    )?;

    if let Some(response) = &endpoint.response {
        let schema = type_repr_to_valibot(response, used);
        writeln!(out, "export const {id}ResponseSchema = {schema};")?;
        writeln!(out)?;
    }

    if let Some(body) = &endpoint.request_body {
        let schema = if endpoint.method == HttpMethod::Patch {
            match body {
                TypeRepr::Ref { name } => {
                    used.mark("lazy");
                    used.mark("partial");
                    format!("partial(lazy(() => {name}Schema))")
                }
                other => type_repr_to_valibot(other, used),
            }
        } else {
            type_repr_to_valibot(body, used)
        };
        writeln!(out, "export const {id}BodySchema = {schema};")?;
        writeln!(out)?;
    }

    if let Some(error) = &endpoint.error_response {
        let schema = type_repr_to_valibot(error, used);
        writeln!(out, "export const {id}ErrorSchema = {schema};")?;
        writeln!(out)?;
    }

    Ok(())
}

fn type_repr_to_valibot(repr: &TypeRepr, used: &mut UsedFunctions) -> String {
    match repr {
        TypeRepr::Primitive(p) => match p {
            PrimitiveType::String => {
                used.mark("string");
                "string()".to_string()
            }
            PrimitiveType::Number | PrimitiveType::Integer => {
                used.mark("number");
                "number()".to_string()
            }
            PrimitiveType::Boolean => {
                used.mark("boolean");
                "boolean()".to_string()
            }
        },
        TypeRepr::Object { properties } => {
            if properties.is_empty() {
                used.mark("record");
                used.mark("string");
                used.mark("unknown");
                return "record(string(), unknown())".to_string();
            }
            used.mark("object");
            let fields: Vec<String> = properties
                .values()
                .map(|p| {
                    let base = type_repr_to_valibot(&p.repr, used);
                    let schema = append_constraints(&base, &p.constraints, used);
                    if p.required {
                        format!("{}: {schema}", p.name)
                    } else {
                        used.mark("optional");
                        format!("{}: optional({schema})", p.name)
                    }
                })
                .collect();
            format!("object({{ {} }})", fields.join(", "))
        }
        TypeRepr::Array { items } => {
            used.mark("array");
            format!("array({})", type_repr_to_valibot(items, used))
        }
        TypeRepr::Union { variants, .. } => {
            if variants.len() == 1 {
                return type_repr_to_valibot(&variants[0], used);
            }
            used.mark("union");
            let schemas: Vec<String> = variants
                .iter()
                .map(|v| type_repr_to_valibot(v, used))
                .collect();
            format!("union([{}])", schemas.join(", "))
        }
        TypeRepr::Ref { name } => {
            used.mark("lazy");
            format!("lazy(() => {name}Schema)")
        }
        TypeRepr::Enum { values } => {
            let all_strings = values.iter().all(|v| matches!(v, EnumValue::String(_)));
            if all_strings && !values.is_empty() {
                used.mark("enum_");
                let vals: Vec<String> = values
                    .iter()
                    .map(|v| match v {
                        EnumValue::String(s) => format!("'{s}'"),
                        EnumValue::Integer(n) => n.to_string(),
                    })
                    .collect();
                format!("enum_([{}])", vals.join(", "))
            } else {
                used.mark("union");
                used.mark("literal");
                let literals: Vec<String> = values
                    .iter()
                    .map(|v| match v {
                        EnumValue::String(s) => format!("literal('{s}')"),
                        EnumValue::Integer(n) => format!("literal({n})"),
                    })
                    .collect();
                format!("union([{}])", literals.join(", "))
            }
        }
        TypeRepr::Tuple { items } => {
            used.mark("tuple");
            let parts: Vec<String> = items
                .iter()
                .map(|i| type_repr_to_valibot(i, used))
                .collect();
            format!("tuple([{}])", parts.join(", "))
        }
        TypeRepr::Nullable(inner) => {
            used.mark("nullable");
            format!("nullable({})", type_repr_to_valibot(inner, used))
        }
        TypeRepr::Map { value } => {
            used.mark("record");
            used.mark("string");
            format!("record(string(), {})", type_repr_to_valibot(value, used))
        }
        TypeRepr::Intersection { members } => {
            used.mark("intersect");
            let parts: Vec<String> = members
                .iter()
                .map(|m| type_repr_to_valibot(m, used))
                .collect();
            format!("intersect([{}])", parts.join(", "))
        }
        TypeRepr::Any => {
            used.mark("unknown");
            "unknown()".to_string()
        }
    }
}

/// Map OpenAPI `format` to Valibot validators via pipe().
fn append_format(schema: &str, format: Option<&str>, used: &mut UsedFunctions) -> String {
    let Some(fmt) = format else {
        return schema.to_string();
    };
    // Only append format validators to string() schemas
    if !schema.starts_with("string()") {
        return schema.to_string();
    }
    let (import, action) = match fmt {
        "email" => ("email", "email()"),
        "uri" | "url" => ("url", "url()"),
        "uuid" => ("uuid", "uuid()"),
        "date-time" => ("isoDateTime", "isoDateTime()"),
        "date" => ("isoDate", "isoDate()"),
        "ip" | "ipv4" => ("ip", "ip()"),
        _ => return schema.to_string(),
    };
    used.mark("pipe");
    used.mark(import);
    format!("pipe({schema}, {action})")
}

/// Valibot v1 uses pipe() for constraints: `pipe(string(), minLength(3), maxLength(50))`
fn append_constraints(schema: &str, c: &Constraints, used: &mut UsedFunctions) -> String {
    let mut actions = Vec::new();

    if let Some(v) = c.min_length {
        used.mark("minLength");
        actions.push(format!("minLength({v})"));
    }
    if let Some(v) = c.max_length {
        used.mark("maxLength");
        actions.push(format!("maxLength({v})"));
    }
    if let Some(v) = &c.pattern {
        used.mark("regex");
        actions.push(format!("regex(/{v}/)"));
    }
    if let Some(v) = c.minimum {
        used.mark("minValue");
        actions.push(format!("minValue({v})"));
    }
    if let Some(v) = c.maximum {
        used.mark("maxValue");
        actions.push(format!("maxValue({v})"));
    }
    if let Some(v) = c.exclusive_minimum {
        used.mark("gtValue");
        actions.push(format!("gtValue({v})"));
    }
    if let Some(v) = c.exclusive_maximum {
        used.mark("ltValue");
        actions.push(format!("ltValue({v})"));
    }
    if let Some(v) = c.multiple_of {
        used.mark("multipleOf");
        actions.push(format!("multipleOf({v})"));
    }
    if let Some(v) = c.min_items {
        used.mark("minLength");
        actions.push(format!("minLength({v})"));
    }
    if let Some(v) = c.max_items {
        used.mark("maxLength");
        actions.push(format!("maxLength({v})"));
    }

    if actions.is_empty() {
        schema.to_string()
    } else {
        used.mark("pipe");
        format!("pipe({schema}, {})", actions.join(", "))
    }
}
