use std::fmt::Write;

use oa_forge_ir::*;

/// Emit @faker-js/faker based mock data factories from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import {{ faker }} from '@faker-js/faker';")?;
    writeln!(out, "import type * as Types from './types.gen';")?;
    writeln!(out)?;

    // Emit mock factories for each named schema type
    for typedef in api.types.values() {
        emit_mock_factory(typedef, out)?;
    }

    // Emit mock factories for endpoint response types
    for endpoint in &api.endpoints {
        emit_endpoint_mock(endpoint, out)?;
    }

    Ok(())
}

fn emit_mock_factory(typedef: &TypeDef, out: &mut String) -> Result<(), std::fmt::Error> {
    let name = &typedef.name;

    match &typedef.repr {
        TypeRepr::Object { properties } => {
            writeln!(
                out,
                "export function mock{name}(overrides?: Partial<Types.{name}>): Types.{name} {{"
            )?;
            writeln!(out, "  return {{")?;
            for prop in properties.values() {
                let faker_expr = type_repr_to_faker(&prop.repr, prop.description.as_deref());
                writeln!(out, "    {}: {},", prop.name, faker_expr)?;
            }
            writeln!(out, "    ...overrides,")?;
            writeln!(out, "  }};")?;
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
        TypeRepr::Enum { values } => {
            let literals: Vec<String> = values
                .iter()
                .map(|v| match v {
                    EnumValue::String(s) => format!("'{s}'"),
                    EnumValue::Integer(n) => n.to_string(),
                })
                .collect();
            writeln!(out, "export function mock{name}(): Types.{name} {{")?;
            writeln!(
                out,
                "  return faker.helpers.arrayElement([{}]) as Types.{name};",
                literals.join(", ")
            )?;
            writeln!(out, "}}")?;
            writeln!(out)?;
        }
        // Skip unions, primitives, etc. — they don't need dedicated factories
        _ => {}
    }

    Ok(())
}

fn emit_endpoint_mock(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;

    if let Some(ref response) = endpoint.response {
        let faker_expr = type_repr_to_faker(response, None);
        writeln!(
            out,
            "export function mock{id}Response(): Types.{id}Response {{"
        )?;
        writeln!(out, "  return {faker_expr};")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    Ok(())
}

/// Convert a TypeRepr to a faker expression that generates matching data.
fn type_repr_to_faker(repr: &TypeRepr, description: Option<&str>) -> String {
    match repr {
        TypeRepr::Primitive(p) => primitive_to_faker(p, description),
        TypeRepr::Object { properties } => {
            if properties.is_empty() {
                return "{}".to_string();
            }
            let fields: Vec<String> = properties
                .values()
                .map(|prop| {
                    let expr = type_repr_to_faker(&prop.repr, prop.description.as_deref());
                    format!("{}: {}", prop.name, expr)
                })
                .collect();
            format!("{{ {} }}", fields.join(", "))
        }
        TypeRepr::Array { items } => {
            let inner = type_repr_to_faker(items, None);
            format!(
                "Array.from({{ length: faker.number.int({{ min: 1, max: 3 }}) }}, () => {inner})"
            )
        }
        TypeRepr::Ref { name } => {
            format!("mock{name}()")
        }
        TypeRepr::Enum { values } => {
            let literals: Vec<String> = values
                .iter()
                .map(|v| match v {
                    EnumValue::String(s) => format!("'{s}'"),
                    EnumValue::Integer(n) => n.to_string(),
                })
                .collect();
            format!("faker.helpers.arrayElement([{}])", literals.join(", "))
        }
        TypeRepr::Nullable(inner) => {
            let expr = type_repr_to_faker(inner, description);
            format!("faker.helpers.maybe(() => {expr}, {{ probability: 0.8 }}) ?? null")
        }
        TypeRepr::Map { value } => {
            let val_expr = type_repr_to_faker(value, None);
            format!(
                "Object.fromEntries(Array.from({{ length: 2 }}, () => [faker.lorem.word(), {val_expr}]))"
            )
        }
        TypeRepr::Union { variants, .. } => {
            if variants.is_empty() {
                return "undefined as any".to_string();
            }
            // Pick a random variant
            let exprs: Vec<String> = variants
                .iter()
                .map(|v| type_repr_to_faker(v, None))
                .collect();
            if exprs.len() == 1 {
                return exprs[0].clone();
            }
            format!("faker.helpers.arrayElement([{}])", exprs.join(", "))
        }
        TypeRepr::Tuple { items } => {
            let parts: Vec<String> = items.iter().map(|i| type_repr_to_faker(i, None)).collect();
            format!("[{}] as const", parts.join(", "))
        }
        TypeRepr::Intersection { members } => {
            // Spread all members into a single object
            let parts: Vec<String> = members
                .iter()
                .map(|m| format!("...{}", type_repr_to_faker(m, None)))
                .collect();
            format!("({{ {} }} as any)", parts.join(", "))
        }
        TypeRepr::Any => "faker.lorem.word()".to_string(),
    }
}

/// Pick the best faker method for a primitive based on description hints.
fn primitive_to_faker(prim: &PrimitiveType, description: Option<&str>) -> String {
    match prim {
        PrimitiveType::String => {
            let desc = description.unwrap_or("").to_lowercase();
            if desc.contains("email") {
                "faker.internet.email()".to_string()
            } else if desc.contains("url") || desc.contains("uri") {
                "faker.internet.url()".to_string()
            } else if desc.contains("name") {
                "faker.person.fullName()".to_string()
            } else if desc.contains("date") || desc.contains("time") {
                "faker.date.recent().toISOString()".to_string()
            } else if desc.contains("uuid") || desc.contains("id") {
                "faker.string.uuid()".to_string()
            } else if desc.contains("phone") {
                "faker.phone.number()".to_string()
            } else if desc.contains("address") {
                "faker.location.streetAddress()".to_string()
            } else {
                "faker.lorem.word()".to_string()
            }
        }
        PrimitiveType::Number => "faker.number.float()".to_string(),
        PrimitiveType::Integer => "faker.number.int()".to_string(),
        PrimitiveType::Boolean => "faker.datatype.boolean()".to_string(),
    }
}
