use std::fmt::Write;

use oa_forge_ir::*;

/// Emit Hono RPC type definitions that enable type-safe `hc` client usage.
/// Generates a `AppType` that matches Hono's route type inference system.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import type * as Types from './types.gen';")?;
    writeln!(out)?;

    // Group endpoints by path for Hono's nested route structure
    let mut paths: indexmap::IndexMap<String, Vec<&Endpoint>> = indexmap::IndexMap::new();
    for ep in &api.endpoints {
        paths.entry(ep.path.clone()).or_default().push(ep);
    }

    writeln!(out, "export type AppType = {{")?;
    for (path, endpoints) in &paths {
        let hono_path = path_to_colon_params(path);
        writeln!(out, "  '{hono_path}': {{")?;

        for ep in endpoints {
            let method = format!("${}", ep.method.as_lower());

            writeln!(out, "    {method}: {{")?;

            // Input type
            writeln!(out, "      input: {{")?;

            // Path params
            if ep.has_params(&ParamLocation::Path) {
                writeln!(out, "        param: Types.{}PathParams;", ep.operation_id)?;
            }

            // Query params
            if ep.has_params(&ParamLocation::Query) {
                writeln!(out, "        query: Types.{}QueryParams;", ep.operation_id)?;
            }

            // Request body
            if ep.request_body.is_some() {
                writeln!(out, "        json: Types.{}Body;", ep.operation_id)?;
            }

            writeln!(out, "      }};")?;

            // Output type
            if let Some(_response) = &ep.response {
                writeln!(out, "      output: Types.{}Response;", ep.operation_id)?;
            } else {
                writeln!(out, "      output: void;")?;
            }

            writeln!(out, "    }};")?;
        }

        writeln!(out, "  }};")?;
    }
    writeln!(out, "}};")?;

    Ok(())
}
