use std::fmt::Write;

use oa_forge_ir::*;

/// Emit Hono RPC type definitions that enable type-safe `hc` client usage.
/// Generates a `AppType` that matches Hono's route type inference system.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import type * as Types from './types.gen';")?;
    writeln!(out)?;

    // Group endpoints by path for Hono's nested route structure
    let mut paths: indexmap::IndexMap<String, Vec<&Endpoint>> = indexmap::IndexMap::new();
    for ep in &api.endpoints {
        paths.entry(ep.path.clone()).or_default().push(ep);
    }

    writeln!(out, "export type AppType = {{")?;
    for (path, endpoints) in &paths {
        let hono_path = to_hono_path(path);
        writeln!(out, "  '{hono_path}': {{")?;

        for ep in endpoints {
            let method = match ep.method {
                HttpMethod::Get => "$get",
                HttpMethod::Post => "$post",
                HttpMethod::Put => "$put",
                HttpMethod::Patch => "$patch",
                HttpMethod::Delete => "$delete",
            };

            writeln!(out, "    {method}: {{")?;

            // Input type
            writeln!(out, "      input: {{")?;

            // Path params
            let path_params: Vec<&EndpointParam> = ep
                .parameters
                .iter()
                .filter(|p| p.location == ParamLocation::Path)
                .collect();
            if !path_params.is_empty() {
                writeln!(out, "        param: Types.{}PathParams;", ep.operation_id)?;
            }

            // Query params
            let query_params: Vec<&EndpointParam> = ep
                .parameters
                .iter()
                .filter(|p| p.location == ParamLocation::Query)
                .collect();
            if !query_params.is_empty() {
                writeln!(out, "        query: Types.{}QueryParams;", ep.operation_id)?;
            }

            // Request body
            if ep.request_body.is_some() {
                writeln!(out, "        json: Types.{}Body;", ep.operation_id)?;
            }

            writeln!(out, "      }};")?;

            // Output type
            if let Some(_response) = &ep.response {
                writeln!(out, "      output: Types.{}Response;", ep.operation_id)?;
            } else {
                writeln!(out, "      output: void;")?;
            }

            writeln!(out, "    }};")?;
        }

        writeln!(out, "  }};")?;
    }
    writeln!(out, "}};")?;

    Ok(())
}

/// Convert OpenAPI path `/pets/{petId}` to Hono path `/pets/:petId`.
fn to_hono_path(path: &str) -> String {
    let mut result = String::with_capacity(path.len());
    for ch in path.chars() {
        match ch {
            '{' => result.push(':'),
            '}' => {}
            _ => result.push(ch),
        }
    }
    result
}
