use std::fmt::Write;

use oa_forge_ir::*;

/// Emit a single endpoint client function (without infrastructure).
pub fn emit_endpoint(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    emit_endpoint_fn(endpoint, out)
}

/// Emit a typed fetch client from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;

    // Collect and emit imports from types.gen
    emit_type_imports(api, out)?;

    // Emit base client helpers
    writeln!(
        out,
        "export type RequestInterceptor = (url: string, init: RequestInit) => RequestInit | Promise<RequestInit>;"
    )?;
    writeln!(
        out,
        "export type ResponseInterceptor = (response: Response) => Response | Promise<Response>;"
    )?;
    writeln!(out)?;
    writeln!(out, "export interface RequestConfig {{")?;
    writeln!(out, "  baseUrl?: string;")?;
    writeln!(out, "  headers?: Record<string, string>;")?;
    writeln!(out, "  signal?: AbortSignal;")?;
    writeln!(
        out,
        "  /** Request timeout in milliseconds. Creates an AbortSignal that aborts after the specified duration. */"
    )?;
    writeln!(out, "  timeout?: number;")?;
    writeln!(
        out,
        "  /** Custom fetch implementation (e.g. for testing or SSR). */"
    )?;
    writeln!(out, "  fetch?: typeof fetch;")?;
    writeln!(
        out,
        "  /** Interceptors applied before sending the request. */"
    )?;
    writeln!(
        out,
        "  onRequest?: RequestInterceptor | RequestInterceptor[];"
    )?;
    writeln!(
        out,
        "  /** Interceptors applied after receiving the response. */"
    )?;
    writeln!(
        out,
        "  onResponse?: ResponseInterceptor | ResponseInterceptor[];"
    )?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Determine which response helpers are needed
    let needs_json = api
        .endpoints
        .iter()
        .any(|e| e.response_type == ResponseType::Json);
    let needs_text = api
        .endpoints
        .iter()
        .any(|e| e.response_type == ResponseType::Text);
    let needs_blob = api
        .endpoints
        .iter()
        .any(|e| e.response_type == ResponseType::Blob);
    let needs_void = api
        .endpoints
        .iter()
        .any(|e| e.response_type == ResponseType::Void && e.request_body.is_some());

    // ApiError class for typed error responses
    writeln!(out, "export class ApiError<T = unknown> extends Error {{")?;
    writeln!(out, "  status: number;")?;
    writeln!(out, "  body: T;")?;
    writeln!(out, "  constructor(status: number, body: T) {{")?;
    writeln!(out, "    super(`HTTP ${{status}}`);")?;
    writeln!(out, "    this.name = 'ApiError';")?;
    writeln!(out, "    this.status = status;")?;
    writeln!(out, "    this.body = body;")?;
    writeln!(out, "  }}")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Resolve signal from config (combines user signal + timeout)
    writeln!(
        out,
        "function resolveSignal(config?: RequestConfig): AbortSignal | undefined {{"
    )?;
    writeln!(out, "  if (!config) return undefined;")?;
    writeln!(out, "  const {{ signal, timeout }} = config;")?;
    writeln!(out, "  if (!timeout) return signal;")?;
    writeln!(out, "  const timeoutSignal = AbortSignal.timeout(timeout);")?;
    writeln!(out, "  if (!signal) return timeoutSignal;")?;
    writeln!(out, "  return AbortSignal.any([signal, timeoutSignal]);")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Apply interceptor chain
    writeln!(out, "async function applyInterceptors<T>(")?;
    writeln!(out, "  value: T,")?;
    writeln!(
        out,
        "  interceptors?: ((v: T) => T | Promise<T>) | ((v: T) => T | Promise<T>)[],"
    )?;
    writeln!(out, "): Promise<T> {{")?;
    writeln!(out, "  if (!interceptors) return value;")?;
    writeln!(
        out,
        "  const fns = Array.isArray(interceptors) ? interceptors : [interceptors];"
    )?;
    writeln!(out, "  let result = value;")?;
    writeln!(out, "  for (const fn of fns) result = await fn(result);")?;
    writeln!(out, "  return result;")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Base fetch helper (always emitted)
    writeln!(out, "async function fetchBase(")?;
    writeln!(out, "  url: string,")?;
    writeln!(out, "  init: RequestInit & {{ baseUrl?: string }},")?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, "): Promise<Response> {{")?;
    writeln!(out, "  const {{ baseUrl = '', ...rest }} = init;")?;
    writeln!(out, "  const fullUrl = `${{baseUrl}}${{url}}`;")?;
    writeln!(
        out,
        "  const finalInit = await applyInterceptors(rest, config?.onRequest as any);"
    )?;
    writeln!(out, "  const fetchFn = config?.fetch ?? fetch;")?;
    writeln!(out, "  let response = await fetchFn(fullUrl, finalInit);")?;
    writeln!(
        out,
        "  response = await applyInterceptors(response, config?.onResponse);"
    )?;
    writeln!(out, "  if (!response.ok) {{")?;
    writeln!(
        out,
        "    const body = await response.json().catch(() => undefined);"
    )?;
    writeln!(out, "    throw new ApiError(response.status, body);")?;
    writeln!(out, "  }}")?;
    writeln!(out, "  return response;")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    if needs_json {
        writeln!(
            out,
            "async function request<T>(url: string, init: RequestInit & {{ baseUrl?: string }}, config?: RequestConfig): Promise<T> {{"
        )?;
        writeln!(
            out,
            "  const response = await fetchBase(url, init, config);"
        )?;
        writeln!(out, "  return response.json();")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    if needs_text {
        writeln!(
            out,
            "async function requestText(url: string, init: RequestInit & {{ baseUrl?: string }}, config?: RequestConfig): Promise<string> {{"
        )?;
        writeln!(
            out,
            "  const response = await fetchBase(url, init, config);"
        )?;
        writeln!(out, "  return response.text();")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    if needs_blob {
        writeln!(
            out,
            "async function requestBlob(url: string, init: RequestInit & {{ baseUrl?: string }}, config?: RequestConfig): Promise<Blob> {{"
        )?;
        writeln!(
            out,
            "  const response = await fetchBase(url, init, config);"
        )?;
        writeln!(out, "  return response.blob();")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    if needs_void {
        writeln!(
            out,
            "async function requestVoid(url: string, init: RequestInit & {{ baseUrl?: string }}, config?: RequestConfig): Promise<void> {{"
        )?;
        writeln!(out, "  await fetchBase(url, init, config);")?;
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    writeln!(out, "type ArrayStyle = 'comma' | 'multi' | 'brackets';")?;
    writeln!(out)?;
    writeln!(out, "function buildQuery(")?;
    writeln!(out, "  params?: Record<string, unknown>,")?;
    writeln!(out, "  arrayStyles?: Record<string, ArrayStyle>,")?;
    writeln!(out, "): string {{")?;
    writeln!(out, "  if (!params) return '';")?;
    writeln!(out, "  const parts: string[] = [];")?;
    writeln!(
        out,
        "  for (const [key, value] of Object.entries(params)) {{"
    )?;
    writeln!(out, "    if (value === undefined) continue;")?;
    writeln!(out, "    if (Array.isArray(value)) {{")?;
    writeln!(out, "      const style = arrayStyles?.[key] ?? 'multi';")?;
    writeln!(out, "      if (style === 'comma') {{")?;
    writeln!(
        out,
        "        parts.push(`${{encodeURIComponent(key)}}=${{value.map(v => encodeURIComponent(String(v))).join(',')}}`);"
    )?;
    writeln!(out, "      }} else if (style === 'brackets') {{")?;
    writeln!(
        out,
        "        for (const v of value) parts.push(`${{encodeURIComponent(key + '[]')}}=${{encodeURIComponent(String(v))}}`);"
    )?;
    writeln!(out, "      }} else {{")?;
    writeln!(
        out,
        "        for (const v of value) parts.push(`${{encodeURIComponent(key)}}=${{encodeURIComponent(String(v))}}`);"
    )?;
    writeln!(out, "      }}")?;
    writeln!(out, "    }} else {{")?;
    writeln!(
        out,
        "      parts.push(`${{encodeURIComponent(key)}}=${{encodeURIComponent(String(value))}}`);"
    )?;
    writeln!(out, "    }}")?;
    writeln!(out, "  }}")?;
    writeln!(
        out,
        "  return parts.length > 0 ? '?' + parts.join('&') : '';"
    )?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Emit endpoint functions
    for endpoint in &api.endpoints {
        emit_endpoint_fn(endpoint, out)?;
        writeln!(out)?;
    }

    Ok(())
}

/// Check whether the endpoint has any params at the given location.
fn has_params(endpoint: &Endpoint, location: ParamLocation) -> bool {
    endpoint.parameters.iter().any(|p| p.location == location)
}

fn emit_type_imports(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    let mut imports = Vec::new();

    let param_suffixes = [
        (ParamLocation::Path, "PathParams"),
        (ParamLocation::Query, "QueryParams"),
        (ParamLocation::Header, "HeaderParams"),
        (ParamLocation::Cookie, "CookieParams"),
    ];

    for endpoint in &api.endpoints {
        let id = &endpoint.operation_id;

        for (location, suffix) in &param_suffixes {
            if has_params(endpoint, location.clone()) {
                imports.push(format!("{id}{suffix}"));
            }
        }
        if endpoint.response.is_some() && endpoint.response_type == ResponseType::Json {
            imports.push(format!("{id}Response"));
        }
        if endpoint.request_body.is_some() {
            imports.push(format!("{id}Body"));
        }
        if endpoint.error_response.is_some() {
            imports.push(format!("{id}Error"));
        }
    }

    if !imports.is_empty() {
        writeln!(
            out,
            "import type {{ {} }} from './types.gen';",
            imports.join(", ")
        )?;
        writeln!(out)?;
    }

    Ok(())
}

fn emit_endpoint_fn(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let method = match endpoint.method {
        HttpMethod::Get => "GET",
        HttpMethod::Post => "POST",
        HttpMethod::Put => "PUT",
        HttpMethod::Patch => "PATCH",
        HttpMethod::Delete => "DELETE",
    };

    // Build parameter list
    let has_path = has_params(endpoint, ParamLocation::Path);
    let has_query = has_params(endpoint, ParamLocation::Query);
    let has_header = has_params(endpoint, ParamLocation::Header);
    let has_cookie = has_params(endpoint, ParamLocation::Cookie);
    let has_body = endpoint.request_body.is_some();

    let mut params = Vec::new();
    if has_path {
        params.push(format!("pathParams: {id}PathParams"));
    }
    if has_query {
        params.push(format!("queryParams?: {id}QueryParams"));
    }
    if has_header {
        params.push(format!("headerParams: {id}HeaderParams"));
    }
    if has_cookie {
        params.push(format!("cookieParams: {id}CookieParams"));
    }
    if has_body {
        params.push(format!("body: {id}Body"));
    }
    params.push("config?: RequestConfig".to_string());

    let return_type = match endpoint.response_type {
        ResponseType::Json if endpoint.response.is_some() => format!("{id}Response"),
        ResponseType::Text => "string".to_string(),
        ResponseType::Blob => "Blob".to_string(),
        _ => "void".to_string(),
    };

    // Build URL with path params
    let url = build_url_template(&endpoint.path);

    // Build query string part (with array style hints)
    let array_params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Query && p.array_style.is_some())
        .collect();

    let url_with_query = if has_query {
        if array_params.is_empty() {
            format!("{url}${{buildQuery(queryParams as Record<string, unknown>)}}")
        } else {
            let styles: Vec<String> = array_params
                .iter()
                .map(|p| {
                    let style = match p.array_style.as_ref().unwrap() {
                        ArrayStyle::Comma => "comma",
                        ArrayStyle::Multi => "multi",
                        ArrayStyle::Brackets => "brackets",
                    };
                    format!("{}: '{}'", p.name, style)
                })
                .collect();
            format!(
                "{url}${{buildQuery(queryParams as Record<string, unknown>, {{ {} }})}}",
                styles.join(", ")
            )
        }
    } else {
        url
    };

    // Build headers
    let headers_expr = if !has_header && !has_cookie {
        // No special params — use the original simple format
        match endpoint.request_content_type {
            ContentType::Json => {
                "{ 'Content-Type': 'application/json', ...config?.headers }".to_string()
            }
            ContentType::TextPlain => {
                "{ 'Content-Type': 'text/plain', ...config?.headers }".to_string()
            }
            ContentType::OctetStream => {
                "{ 'Content-Type': 'application/octet-stream', ...config?.headers }".to_string()
            }
            ContentType::FormData | ContentType::None => "config?.headers".to_string(),
        }
    } else {
        let mut parts = Vec::new();
        match endpoint.request_content_type {
            ContentType::Json => parts.push("'Content-Type': 'application/json'".to_string()),
            ContentType::TextPlain => parts.push("'Content-Type': 'text/plain'".to_string()),
            ContentType::OctetStream => {
                parts.push("'Content-Type': 'application/octet-stream'".to_string())
            }
            ContentType::FormData | ContentType::None => {}
        }
        if has_header {
            parts.push("...headerParams as Record<string, string>".to_string());
        }
        if has_cookie {
            parts.push("Cookie: Object.entries(cookieParams).filter(([, v]) => v !== undefined).map(([k, v]) => `${k}=${v}`).join('; ')".to_string());
        }
        parts.push("...config?.headers".to_string());
        format!("{{ {} }}", parts.join(", "))
    };

    // Choose the right request function
    let request_fn = match endpoint.response_type {
        ResponseType::Json => format!("request<{return_type}>"),
        ResponseType::Text => "requestText".to_string(),
        ResponseType::Blob => "requestBlob".to_string(),
        ResponseType::Void => {
            if has_body {
                "requestVoid".to_string()
            } else {
                // For void without body (e.g. DELETE), use fetchBase directly
                "fetchBase".to_string()
            }
        }
    };

    writeln!(
        out,
        "export function {id}({}): Promise<{return_type}> {{",
        params.join(", ")
    )?;

    if endpoint.response_type == ResponseType::Void && !has_body {
        // Void without request body — fire and forget
        writeln!(
            out,
            "  return fetchBase(`${{config?.baseUrl ?? ''}}{url_with_query}`, {{"
        )?;
        writeln!(out, "    method: '{method}',")?;
        writeln!(out, "    headers: {headers_expr},")?;
        writeln!(out, "    signal: resolveSignal(config),")?;
        writeln!(out, "  }}, config).then(() => {{}});")?;
    } else {
        writeln!(
            out,
            "  return {request_fn}(`${{config?.baseUrl ?? ''}}{url_with_query}`, {{"
        )?;
        writeln!(out, "    method: '{method}',")?;
        writeln!(out, "    headers: {headers_expr},")?;
        writeln!(out, "    signal: resolveSignal(config),")?;
        if has_body {
            match endpoint.request_content_type {
                ContentType::Json => writeln!(out, "    body: JSON.stringify(body),")?,
                ContentType::FormData => {
                    writeln!(out, "    body: (() => {{")?;
                    writeln!(out, "      const fd = new FormData();")?;
                    writeln!(
                        out,
                        "      for (const [k, v] of Object.entries(body as Record<string, unknown>)) {{"
                    )?;
                    writeln!(out, "        if (v instanceof Blob) fd.append(k, v);")?;
                    writeln!(
                        out,
                        "        else if (v !== undefined) fd.append(k, String(v));"
                    )?;
                    writeln!(out, "      }}")?;
                    writeln!(out, "      return fd;")?;
                    writeln!(out, "    }})(),")?;
                }
                ContentType::TextPlain => writeln!(out, "    body: String(body),")?,
                ContentType::OctetStream => writeln!(out, "    body: body as any,")?,
                ContentType::None => {}
            }
        }
        writeln!(out, "  }}, config);")?;
    }
    writeln!(out, "}}")?;

    Ok(())
}

/// Convert OpenAPI path `/users/{userId}` to template literal `/users/${pathParams.userId}`
fn build_url_template(path: &str) -> String {
    let mut result = String::new();
    let mut chars = path.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '{' {
            let param_name: String = chars.by_ref().take_while(|&c| c != '}').collect();
            result.push_str(&format!("${{pathParams.{param_name}}}"));
        } else {
            result.push(c);
        }
    }

    result
}
