use std::fmt::Write;

use oa_forge_ir::*;

/// Emit a typed fetch client from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;

    // Collect and emit imports from types.gen
    emit_type_imports(api, out)?;

    // Emit base client helper
    writeln!(out, "export interface RequestConfig {{")?;
    writeln!(out, "  baseUrl?: string;")?;
    writeln!(out, "  headers?: Record<string, string>;")?;
    writeln!(out, "  signal?: AbortSignal;")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(out, "async function request<T>(url: string, init: RequestInit & {{ baseUrl?: string }}): Promise<T> {{")?;
    writeln!(out, "  const {{ baseUrl = '', ...rest }} = init;")?;
    writeln!(out, "  const response = await fetch(`${{baseUrl}}${{url}}`, rest);")?;
    writeln!(out, "  if (!response.ok) throw new Error(`HTTP ${{response.status}}`);")?;
    writeln!(out, "  return response.json();")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    writeln!(out, "function buildQuery(params?: Record<string, unknown>): string {{")?;
    writeln!(out, "  if (!params) return '';")?;
    writeln!(out, "  const entries = Object.entries(params).filter(([, v]) => v !== undefined);")?;
    writeln!(out, "  if (entries.length === 0) return '';")?;
    writeln!(out, "  return '?' + new URLSearchParams(entries.map(([k, v]) => [k, String(v)])).toString();")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // Emit endpoint functions
    for endpoint in &api.endpoints {
        emit_endpoint_fn(endpoint, out)?;
        writeln!(out)?;
    }

    Ok(())
}

fn emit_type_imports(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    let mut imports = Vec::new();

    for endpoint in &api.endpoints {
        let id = &endpoint.operation_id;
        let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
        let has_query = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Query);

        if has_path {
            imports.push(format!("{id}PathParams"));
        }
        if has_query {
            imports.push(format!("{id}QueryParams"));
        }
        if endpoint.response.is_some() {
            imports.push(format!("{id}Response"));
        }
        if endpoint.request_body.is_some() {
            imports.push(format!("{id}Body"));
        }
    }

    if !imports.is_empty() {
        writeln!(out, "import type {{ {} }} from './types.gen';", imports.join(", "))?;
        writeln!(out)?;
    }

    Ok(())
}

fn emit_endpoint_fn(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let method = match endpoint.method {
        HttpMethod::Get => "GET",
        HttpMethod::Post => "POST",
        HttpMethod::Put => "PUT",
        HttpMethod::Patch => "PATCH",
        HttpMethod::Delete => "DELETE",
    };

    // Build parameter list
    let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
    let has_query = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Query);
    let has_body = endpoint.request_body.is_some();

    let mut params = Vec::new();
    if has_path {
        params.push(format!("pathParams: {id}PathParams"));
    }
    if has_query {
        params.push(format!("queryParams?: {id}QueryParams"));
    }
    if has_body {
        params.push(format!("body: {id}Body"));
    }
    params.push("config?: RequestConfig".to_string());

    let return_type = if endpoint.response.is_some() {
        format!("{id}Response")
    } else {
        "void".to_string()
    };

    // Build URL with path params
    let url = build_url_template(&endpoint.path);

    // Build query string part
    let url_with_query = if has_query {
        format!("{url}${{buildQuery(queryParams)}}")
    } else {
        url
    };

    // Build headers
    let headers_expr = if has_body {
        "{ 'Content-Type': 'application/json', ...config?.headers }"
    } else {
        "config?.headers"
    };

    writeln!(out, "export function {id}({}) {{", params.join(", "))?;
    writeln!(out, "  return request<{return_type}>(`${{config?.baseUrl ?? ''}}{url_with_query}`, {{")?;
    writeln!(out, "    method: '{method}',")?;
    writeln!(out, "    headers: {headers_expr},")?;
    writeln!(out, "    signal: config?.signal,")?;
    if has_body {
        writeln!(out, "    body: JSON.stringify(body),")?;
    }
    writeln!(out, "  }});")?;
    writeln!(out, "}}")?;

    Ok(())
}

/// Convert OpenAPI path `/users/{userId}` to template literal `/users/${pathParams.userId}`
fn build_url_template(path: &str) -> String {
    let mut result = String::new();
    let mut chars = path.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '{' {
            let param_name: String = chars.by_ref().take_while(|&c| c != '}').collect();
            result.push_str(&format!("${{pathParams.{param_name}}}"));
        } else {
            result.push(c);
        }
    }

    result
}
