use std::fmt::Write;

use oa_forge_ir::*;

/// Emit an Axios-based typed client from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;

    emit_type_imports(api, out)?;

    writeln!(out, "import type {{ AxiosInstance, AxiosRequestConfig }} from 'axios';")?;
    writeln!(out, "import axios from 'axios';")?;
    writeln!(out)?;

    // Default instance
    writeln!(out, "let _instance: AxiosInstance = axios.create();")?;
    writeln!(out)?;
    writeln!(out, "export function setAxiosInstance(instance: AxiosInstance) {{")?;
    writeln!(out, "  _instance = instance;")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    // buildQuery helper (same as fetch client)
    emit_build_query(out)?;

    // Emit endpoint functions
    for endpoint in &api.endpoints {
        emit_endpoint_fn(endpoint, out)?;
        writeln!(out)?;
    }

    Ok(())
}

fn emit_type_imports(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    let mut imports = Vec::new();

    for endpoint in &api.endpoints {
        let id = &endpoint.operation_id;
        let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
        let has_query = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Query);

        if has_path {
            imports.push(format!("{id}PathParams"));
        }
        if has_query {
            imports.push(format!("{id}QueryParams"));
        }
        if endpoint.response.is_some() && endpoint.response_type == ResponseType::Json {
            imports.push(format!("{id}Response"));
        }
        if endpoint.request_body.is_some() {
            imports.push(format!("{id}Body"));
        }
    }

    if !imports.is_empty() {
        writeln!(out, "import type {{ {} }} from './types.gen';", imports.join(", "))?;
    }

    Ok(())
}

fn emit_build_query(out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "type ArrayStyle = 'comma' | 'multi' | 'brackets';")?;
    writeln!(out)?;
    writeln!(out, "function buildQuery(")?;
    writeln!(out, "  params?: Record<string, unknown>,")?;
    writeln!(out, "  arrayStyles?: Record<string, ArrayStyle>,")?;
    writeln!(out, "): string {{")?;
    writeln!(out, "  if (!params) return '';")?;
    writeln!(out, "  const parts: string[] = [];")?;
    writeln!(out, "  for (const [key, value] of Object.entries(params)) {{")?;
    writeln!(out, "    if (value === undefined) continue;")?;
    writeln!(out, "    if (Array.isArray(value)) {{")?;
    writeln!(out, "      const style = arrayStyles?.[key] ?? 'multi';")?;
    writeln!(out, "      if (style === 'comma') {{")?;
    writeln!(out, "        parts.push(`${{encodeURIComponent(key)}}=${{value.map(v => encodeURIComponent(String(v))).join(',')}}`);")?;
    writeln!(out, "      }} else if (style === 'brackets') {{")?;
    writeln!(out, "        for (const v of value) parts.push(`${{encodeURIComponent(key + '[]')}}=${{encodeURIComponent(String(v))}}`);")?;
    writeln!(out, "      }} else {{")?;
    writeln!(out, "        for (const v of value) parts.push(`${{encodeURIComponent(key)}}=${{encodeURIComponent(String(v))}}`);")?;
    writeln!(out, "      }}")?;
    writeln!(out, "    }} else {{")?;
    writeln!(out, "      parts.push(`${{encodeURIComponent(key)}}=${{encodeURIComponent(String(value))}}`);")?;
    writeln!(out, "    }}")?;
    writeln!(out, "  }}")?;
    writeln!(out, "  return parts.length > 0 ? '?' + parts.join('&') : '';")?;
    writeln!(out, "}}")?;
    writeln!(out)?;
    Ok(())
}

fn emit_endpoint_fn(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let method = match endpoint.method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
    };

    let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
    let has_query = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Query);
    let has_body = endpoint.request_body.is_some();

    let mut params = Vec::new();
    if has_path {
        params.push(format!("pathParams: {id}PathParams"));
    }
    if has_query {
        params.push(format!("queryParams?: {id}QueryParams"));
    }
    if has_body {
        params.push(format!("body: {id}Body"));
    }
    params.push("config?: AxiosRequestConfig".to_string());

    let return_type = match endpoint.response_type {
        ResponseType::Json if endpoint.response.is_some() => format!("{id}Response"),
        ResponseType::Text => "string".to_string(),
        ResponseType::Blob => "Blob".to_string(),
        _ => "void".to_string(),
    };

    let url = build_url_template(&endpoint.path);

    // Build query string
    let array_params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Query && p.array_style.is_some())
        .collect();

    let url_with_query = if has_query {
        if array_params.is_empty() {
            format!("{url}${{buildQuery(queryParams as Record<string, unknown>)}}")
        } else {
            let styles: Vec<String> = array_params
                .iter()
                .map(|p| {
                    let style = match p.array_style.as_ref().unwrap() {
                        ArrayStyle::Comma => "comma",
                        ArrayStyle::Multi => "multi",
                        ArrayStyle::Brackets => "brackets",
                    };
                    format!("{}: '{}'", p.name, style)
                })
                .collect();
            format!(
                "{url}${{buildQuery(queryParams as Record<string, unknown>, {{ {} }})}}",
                styles.join(", ")
            )
        }
    } else {
        url
    };

    writeln!(
        out,
        "export async function {id}({params}): Promise<{return_type}> {{",
        params = params.join(", ")
    )?;

    let response_type_hint = match endpoint.response_type {
        ResponseType::Text => ", { ...config, responseType: 'text' }",
        ResponseType::Blob => ", { ...config, responseType: 'blob' }",
        _ => ", config",
    };

    if has_body {
        let body_expr = match endpoint.request_content_type {
            ContentType::FormData => {
                writeln!(out, "  const fd = new FormData();")?;
                writeln!(out, "  for (const [k, v] of Object.entries(body as Record<string, unknown>)) {{")?;
                writeln!(out, "    if (v instanceof Blob) fd.append(k, v);")?;
                writeln!(out, "    else if (v !== undefined) fd.append(k, String(v));")?;
                writeln!(out, "  }}")?;
                "fd"
            }
            _ => "body",
        };

        writeln!(
            out,
            "  const {{ data }} = await _instance.{method}<{return_type}>(`{url_with_query}`, {body_expr}{response_type_hint});"
        )?;
    } else if matches!(endpoint.method, HttpMethod::Post | HttpMethod::Put | HttpMethod::Patch) {
        writeln!(
            out,
            "  const {{ data }} = await _instance.{method}<{return_type}>(`{url_with_query}`, undefined{response_type_hint});"
        )?;
    } else {
        writeln!(
            out,
            "  const {{ data }} = await _instance.{method}<{return_type}>(`{url_with_query}`{response_type_hint});"
        )?;
    }

    if return_type == "void" {
        // Don't return data for void responses
    } else {
        writeln!(out, "  return data;")?;
    }

    writeln!(out, "}}")?;

    Ok(())
}

fn build_url_template(path: &str) -> String {
    let mut result = String::new();
    let mut chars = path.chars().peekable();

    while let Some(c) = chars.next() {
        if c == '{' {
            let param_name: String = chars.by_ref().take_while(|&c| c != '}').collect();
            result.push_str(&format!("${{pathParams.{param_name}}}"));
        } else {
            result.push(c);
        }
    }

    result
}
