use std::fmt::Write;

use oa_forge_ir::*;

/// Emit Zod schemas from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out, "import {{ z }} from 'zod';")?;
    writeln!(out)?;

    for typedef in api.types.values() {
        emit_schema_def(typedef, out)?;
        writeln!(out)?;
    }

    for endpoint in &api.endpoints {
        emit_endpoint_schemas(endpoint, out)?;
    }

    Ok(())
}

fn emit_schema_def(typedef: &TypeDef, out: &mut String) -> Result<(), std::fmt::Error> {
    let base = type_repr_to_zod(&typedef.repr);
    let schema = append_constraints(&base, &typedef.constraints);

    match &typedef.repr {
        TypeRepr::Ref { name } => {
            writeln!(
                out,
                "export const {name}Schema = z.lazy(() => {name}Schema);",
            )?;
        }
        _ => {
            if let Some(default) = &typedef.default_value {
                let default_str = serde_json_to_zod_default(default);
                writeln!(
                    out,
                    "export const {}Schema = {schema}.default({default_str});",
                    typedef.name
                )?;
            } else {
                writeln!(out, "export const {}Schema = {schema};", typedef.name)?;
            }
        }
    }

    // Export inferred type
    writeln!(
        out,
        "export type {} = z.infer<typeof {}Schema>;",
        typedef.name, typedef.name
    )?;

    Ok(())
}

fn emit_endpoint_schemas(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;

    // Path params schema
    let path_params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Path)
        .collect();

    if !path_params.is_empty() {
        write!(out, "export const {id}PathParamsSchema = z.object({{")?;
        for p in &path_params {
            let schema = type_repr_to_zod(&p.repr);
            write!(out, " {}: {schema},", p.name)?;
        }
        writeln!(out, " }});")?;
        writeln!(out)?;
    }

    // Query params schema
    let query_params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Query)
        .collect();

    if !query_params.is_empty() {
        write!(out, "export const {id}QueryParamsSchema = z.object({{")?;
        for p in &query_params {
            let schema = type_repr_to_zod(&p.repr);
            if p.required {
                write!(out, " {}: {schema},", p.name)?;
            } else {
                write!(out, " {}: {schema}.optional(),", p.name)?;
            }
        }
        writeln!(out, " }});")?;
        writeln!(out)?;
    }

    // Response schema
    if let Some(response) = &endpoint.response {
        let schema = type_repr_to_zod(response);
        writeln!(out, "export const {id}ResponseSchema = {schema};")?;
        writeln!(out)?;
    }

    // Request body schema
    if let Some(body) = &endpoint.request_body {
        let schema = if endpoint.method == HttpMethod::Patch {
            match body {
                TypeRepr::Ref { name } => format!("z.lazy(() => {name}Schema).partial()"),
                other => type_repr_to_zod(other),
            }
        } else {
            type_repr_to_zod(body)
        };
        writeln!(out, "export const {id}BodySchema = {schema};")?;
        writeln!(out)?;
    }

    // Error response schema
    if let Some(error) = &endpoint.error_response {
        let schema = type_repr_to_zod(error);
        writeln!(out, "export const {id}ErrorSchema = {schema};")?;
        writeln!(out)?;
    }

    Ok(())
}

fn type_repr_to_zod(repr: &TypeRepr) -> String {
    match repr {
        TypeRepr::Primitive(p) => match p {
            PrimitiveType::String => "z.string()".to_string(),
            PrimitiveType::Number | PrimitiveType::Integer => "z.number()".to_string(),
            PrimitiveType::Boolean => "z.boolean()".to_string(),
        },
        TypeRepr::Object { properties } => {
            if properties.is_empty() {
                return "z.record(z.string(), z.unknown())".to_string();
            }
            let fields: Vec<String> = properties
                .values()
                .map(|p| {
                    let base = type_repr_to_zod(&p.repr);
                    let schema = append_constraints(&base, &p.constraints);
                    let with_default = if let Some(dv) = &p.default_value {
                        let default_str = serde_json_to_zod_default(dv);
                        format!("{schema}.default({default_str})")
                    } else {
                        schema
                    };
                    if p.required {
                        format!("{}: {with_default}", p.name)
                    } else {
                        format!("{}: {with_default}.optional()", p.name)
                    }
                })
                .collect();
            format!("z.object({{ {} }})", fields.join(", "))
        }
        TypeRepr::Array { items } => {
            format!("z.array({})", type_repr_to_zod(items))
        }
        TypeRepr::Union { variants, .. } => {
            if variants.len() == 1 {
                return type_repr_to_zod(&variants[0]);
            }
            let schemas: Vec<String> = variants.iter().map(type_repr_to_zod).collect();
            format!("z.union([{}])", schemas.join(", "))
        }
        TypeRepr::Ref { name } => format!("z.lazy(() => {name}Schema)"),
        TypeRepr::Enum { values } => {
            let vals: Vec<String> = values
                .iter()
                .map(|v| match v {
                    EnumValue::String(s) => format!("'{s}'"),
                    EnumValue::Integer(n) => n.to_string(),
                })
                .collect();
            // String enums use z.enum(), mixed/integer use z.union of z.literal
            let all_strings = values.iter().all(|v| matches!(v, EnumValue::String(_)));
            if all_strings && !vals.is_empty() {
                format!("z.enum([{}])", vals.join(", "))
            } else {
                let literals: Vec<String> = values
                    .iter()
                    .map(|v| match v {
                        EnumValue::String(s) => format!("z.literal('{s}')"),
                        EnumValue::Integer(n) => format!("z.literal({n})"),
                    })
                    .collect();
                format!("z.union([{}])", literals.join(", "))
            }
        }
        TypeRepr::Tuple { items } => {
            let parts: Vec<String> = items.iter().map(type_repr_to_zod).collect();
            format!("z.tuple([{}])", parts.join(", "))
        }
        TypeRepr::Nullable(inner) => {
            format!("{}.nullable()", type_repr_to_zod(inner))
        }
        TypeRepr::Map { value } => {
            format!("z.record(z.string(), {})", type_repr_to_zod(value))
        }
        TypeRepr::Intersection { members } => {
            let mut iter = members.iter();
            let first = iter.next().map(type_repr_to_zod).unwrap_or_default();
            iter.fold(first, |acc, m| {
                format!("{acc}.and({})", type_repr_to_zod(m))
            })
        }
        TypeRepr::Any => "z.unknown()".to_string(),
    }
}

fn append_constraints(schema: &str, c: &Constraints) -> String {
    let mut s = schema.to_string();
    if let Some(v) = c.min_length {
        s = format!("{s}.min({v})");
    }
    if let Some(v) = c.max_length {
        s = format!("{s}.max({v})");
    }
    if let Some(v) = &c.pattern {
        s = format!("{s}.regex(/{v}/)");
    }
    if let Some(v) = c.minimum {
        s = format!("{s}.min({v})");
    }
    if let Some(v) = c.maximum {
        s = format!("{s}.max({v})");
    }
    if let Some(v) = c.exclusive_minimum {
        s = format!("{s}.gt({v})");
    }
    if let Some(v) = c.exclusive_maximum {
        s = format!("{s}.lt({v})");
    }
    if let Some(v) = c.multiple_of {
        s = format!("{s}.multipleOf({v})");
    }
    if let Some(v) = c.min_items {
        s = format!("{s}.min({v})");
    }
    if let Some(v) = c.max_items {
        s = format!("{s}.max({v})");
    }
    s
}

fn serde_json_to_zod_default(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::String(s) => format!("'{s}'"),
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::Bool(b) => b.to_string(),
        serde_json::Value::Null => "null".to_string(),
        serde_json::Value::Array(arr) => {
            let items: Vec<String> = arr.iter().map(serde_json_to_zod_default).collect();
            format!("[{}]", items.join(", "))
        }
        serde_json::Value::Object(obj) => {
            let fields: Vec<String> = obj
                .iter()
                .map(|(k, v)| format!("{k}: {}", serde_json_to_zod_default(v)))
                .collect();
            format!("{{ {} }}", fields.join(", "))
        }
    }
}
