use std::fmt::Write;

use oa_forge_ir::*;

/// Emit TypeScript type definitions from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;

    // Emit component schemas as types/interfaces
    for typedef in api.types.values() {
        emit_typedef(typedef, out)?;
        writeln!(out)?;
    }

    // Emit endpoint request/response types
    for endpoint in &api.endpoints {
        emit_endpoint_types(endpoint, out)?;
    }

    Ok(())
}

fn emit_typedef(typedef: &TypeDef, out: &mut String) -> Result<(), std::fmt::Error> {
    match &typedef.repr {
        TypeRepr::Object { properties } => {
            writeln!(out, "export interface {} {{", typedef.name)?;
            for prop in properties.values() {
                let optional = if prop.required { "" } else { "?" };
                let ts_type = type_repr_to_ts(&prop.repr);
                writeln!(out, "  {}{}: {};", prop.name, optional, ts_type)?;
            }
            writeln!(out, "}}")?;
        }
        TypeRepr::Union { variants, .. } => {
            let types: Vec<String> = variants.iter().map(type_repr_to_ts).collect();
            writeln!(out, "export type {} = {};", typedef.name, types.join(" | "))?;
        }
        TypeRepr::Enum { values } => {
            let vals: Vec<String> = values
                .iter()
                .map(|v| match v {
                    EnumValue::String(s) => format!("'{s}'"),
                    EnumValue::Integer(n) => n.to_string(),
                })
                .collect();
            writeln!(out, "export type {} = {};", typedef.name, vals.join(" | "))?;
        }
        other => {
            writeln!(out, "export type {} = {};", typedef.name, type_repr_to_ts(other))?;
        }
    }
    Ok(())
}

fn emit_endpoint_types(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;

    // Path params type
    let path_params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Path)
        .collect();

    if !path_params.is_empty() {
        writeln!(out, "export interface {id}PathParams {{")?;
        for p in &path_params {
            let ts = type_repr_to_ts(&p.repr);
            writeln!(out, "  {}: {};", p.name, ts)?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    // Query params type
    let query_params: Vec<&EndpointParam> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Query)
        .collect();

    if !query_params.is_empty() {
        writeln!(out, "export interface {id}QueryParams {{")?;
        for p in &query_params {
            let optional = if p.required { "" } else { "?" };
            let ts = type_repr_to_ts(&p.repr);
            writeln!(out, "  {}{}: {};", p.name, optional, ts)?;
        }
        writeln!(out, "}}")?;
        writeln!(out)?;
    }

    // Response type
    if let Some(response) = &endpoint.response {
        let ts = type_repr_to_ts(response);
        writeln!(out, "export type {id}Response = {ts};")?;
        writeln!(out)?;
    }

    // Request body type
    if let Some(body) = &endpoint.request_body {
        let ts = type_repr_to_ts(body);
        writeln!(out, "export type {id}Body = {ts};")?;
        writeln!(out)?;
    }

    Ok(())
}

fn type_repr_to_ts(repr: &TypeRepr) -> String {
    match repr {
        TypeRepr::Primitive(p) => match p {
            PrimitiveType::String => "string".to_string(),
            PrimitiveType::Number | PrimitiveType::Integer => "number".to_string(),
            PrimitiveType::Boolean => "boolean".to_string(),
        },
        TypeRepr::Object { properties } => {
            if properties.is_empty() {
                return "Record<string, unknown>".to_string();
            }
            let fields: Vec<String> = properties
                .values()
                .map(|p| {
                    let opt = if p.required { "" } else { "?" };
                    format!("{}{}: {}", p.name, opt, type_repr_to_ts(&p.repr))
                })
                .collect();
            format!("{{ {} }}", fields.join("; "))
        }
        TypeRepr::Array { items } => format!("{}[]", type_repr_to_ts(items)),
        TypeRepr::Union { variants, .. } => {
            let types: Vec<String> = variants.iter().map(type_repr_to_ts).collect();
            types.join(" | ")
        }
        TypeRepr::Ref { name } => name.clone(),
        TypeRepr::Enum { values } => {
            let vals: Vec<String> = values
                .iter()
                .map(|v| match v {
                    EnumValue::String(s) => format!("'{s}'"),
                    EnumValue::Integer(n) => n.to_string(),
                })
                .collect();
            vals.join(" | ")
        }
        TypeRepr::Nullable(inner) => format!("{} | null", type_repr_to_ts(inner)),
        TypeRepr::Any => "unknown".to_string(),
    }
}
