use std::fmt::Write;

use oa_forge_ir::*;

/// Emit TanStack Query v5 hooks from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import {{ useQuery, useMutation, useSuspenseQuery, queryOptions }} from '@tanstack/react-query';")?;
    writeln!(out, "import type {{ UseQueryOptions, UseMutationOptions }} from '@tanstack/react-query';")?;

    // Collect imports
    emit_imports(api, out)?;
    writeln!(out)?;

    for endpoint in &api.endpoints {
        match endpoint.method {
            HttpMethod::Get => emit_query_hook(endpoint, out)?,
            HttpMethod::Post | HttpMethod::Put | HttpMethod::Patch | HttpMethod::Delete => {
                emit_mutation_hook(endpoint, out)?;
            }
        }
        writeln!(out)?;
    }

    Ok(())
}

fn emit_imports(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    let mut type_imports = Vec::new();
    let mut fn_imports = Vec::new();

    for endpoint in &api.endpoints {
        let id = &endpoint.operation_id;
        let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
        let has_query = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Query);

        if has_path {
            type_imports.push(format!("{id}PathParams"));
        }
        if has_query {
            type_imports.push(format!("{id}QueryParams"));
        }
        if endpoint.response.is_some() {
            type_imports.push(format!("{id}Response"));
        }
        if endpoint.request_body.is_some() {
            type_imports.push(format!("{id}Body"));
        }

        fn_imports.push(id.clone());
    }

    if !type_imports.is_empty() {
        writeln!(out, "import type {{ {} }} from './types.gen';", type_imports.join(", "))?;
    }

    writeln!(out, "import type {{ RequestConfig }} from './client.gen';")?;
    writeln!(out, "import {{ {} }} from './client.gen';", fn_imports.join(", "))?;

    Ok(())
}

fn emit_query_hook(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let response_type = format!("{id}Response");
    let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
    let has_query = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Query);

    // Build params type for the combined hook signature
    let params_type = build_params_type(id, has_path, has_query);
    let has_params = has_path || has_query;

    // Build the client call arguments
    let client_call = build_client_call(id, has_path, has_query);

    // queryKey function
    if let Some(pt) = &params_type {
        writeln!(out, "export const {id}QueryKey = (params?: {pt}) =>")?;
        writeln!(out, "  ['{id}', ...(params ? [params] : [])] as const;")?;
    } else {
        writeln!(out, "export const {id}QueryKey = () =>")?;
        writeln!(out, "  ['{id}'] as const;")?;
    }
    writeln!(out)?;

    // queryOptions function
    if has_params {
        writeln!(out, "export const {id}Options = (params?: {}, config?: RequestConfig) =>", params_type.as_deref().unwrap())?;
    } else {
        writeln!(out, "export const {id}Options = (config?: RequestConfig) =>")?;
    }
    writeln!(out, "  queryOptions({{")?;
    if has_params {
        writeln!(out, "    queryKey: {id}QueryKey(params),")?;
        writeln!(out, "    queryFn: () => {client_call},")?;
    } else {
        writeln!(out, "    queryKey: {id}QueryKey(),")?;
        writeln!(out, "    queryFn: () => {id}(config),")?;
    }
    writeln!(out, "  }});")?;
    writeln!(out)?;

    // useQuery hook
    writeln!(out, "export const use{} = (", capitalize(id))?;
    if has_params {
        writeln!(out, "  params?: {},", params_type.as_deref().unwrap())?;
    }
    writeln!(out, "  options?: Partial<UseQueryOptions<{response_type}>>,")?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    if has_params {
        writeln!(out, "  useQuery({{ ...{id}Options(params, config), ...options }});")?;
    } else {
        writeln!(out, "  useQuery({{ ...{id}Options(config), ...options }});")?;
    }
    writeln!(out)?;

    // useSuspenseQuery hook
    writeln!(out, "export const use{}Suspense = (", capitalize(id))?;
    if has_params {
        writeln!(out, "  params?: {},", params_type.as_deref().unwrap())?;
    }
    writeln!(out, "  options?: Partial<UseQueryOptions<{response_type}>>,")?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    if has_params {
        writeln!(out, "  useSuspenseQuery({{ ...{id}Options(params, config), ...options }});")?;
    } else {
        writeln!(out, "  useSuspenseQuery({{ ...{id}Options(config), ...options }});")?;
    }

    Ok(())
}

fn emit_mutation_hook(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let has_path = endpoint.parameters.iter().any(|p| p.location == ParamLocation::Path);
    let has_body = endpoint.request_body.is_some();

    let response_type = if endpoint.response.is_some() {
        format!("{id}Response")
    } else {
        "void".to_string()
    };

    // Determine mutation variables type
    let variables_type = match (has_path, has_body) {
        (true, true) => format!("{{ pathParams: {id}PathParams; body: {id}Body }}"),
        (true, false) => format!("{id}PathParams"),
        (false, true) => format!("{id}Body"),
        (false, false) => "void".to_string(),
    };

    // Build mutationFn body
    let mutation_fn = match (has_path, has_body) {
        (true, true) => format!("(vars: {variables_type}) => {id}(vars.pathParams, vars.body, config)"),
        (true, false) => format!("(pathParams: {id}PathParams) => {id}(pathParams, config)"),
        (false, true) => format!("(body: {id}Body) => {id}(body, config)"),
        (false, false) => format!("() => {id}(config)"),
    };

    writeln!(out, "export const use{} = (", capitalize(id))?;
    writeln!(out, "  options?: UseMutationOptions<{response_type}, Error, {variables_type}>,")?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    writeln!(out, "  useMutation({{")?;
    writeln!(out, "    mutationFn: {mutation_fn},")?;
    writeln!(out, "    ...options,")?;
    writeln!(out, "  }});")?;

    Ok(())
}

/// Build a combined params type string for hook signatures.
fn build_params_type(id: &str, has_path: bool, has_query: bool) -> Option<String> {
    match (has_path, has_query) {
        (true, true) => Some(format!("{id}PathParams & {id}QueryParams")),
        (true, false) => Some(format!("{id}PathParams")),
        (false, true) => Some(format!("{id}QueryParams")),
        (false, false) => None,
    }
}

/// Build the client function call, splitting combined params back into separate args.
fn build_client_call(id: &str, has_path: bool, has_query: bool) -> String {
    match (has_path, has_query) {
        (true, true) => format!("{id}(params!, params, config)"),
        (true, false) => format!("{id}(params!, config)"),
        (false, true) => format!("{id}(params, config)"),
        (false, false) => format!("{id}(config)"),
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}
