use std::fmt::Write;

use oa_forge_ir::*;

/// Target query framework for code generation.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum QueryFramework {
    #[default]
    React,
    Vue,
    Solid,
    Svelte,
}

impl QueryFramework {
    /// Package name for imports.
    fn package(&self) -> &'static str {
        match self {
            Self::React => "@tanstack/react-query",
            Self::Vue => "@tanstack/vue-query",
            Self::Solid => "@tanstack/solid-query",
            Self::Svelte => "@tanstack/svelte-query",
        }
    }

    /// Prefix for hook/function names (e.g., "use" or "create").
    fn hook_prefix(&self) -> &'static str {
        match self {
            Self::React | Self::Vue => "use",
            Self::Solid | Self::Svelte => "create",
        }
    }

    /// Type prefix for options types (e.g., "Use" or "Create").
    fn type_prefix(&self) -> &'static str {
        match self {
            Self::React | Self::Vue => "Use",
            Self::Solid | Self::Svelte => "Create",
        }
    }
}

/// Emit TanStack Query v5 hooks from the API spec (React framework).
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    emit_for(api, out, QueryFramework::React)
}

/// Emit TanStack Query v5 hooks for a specific framework.
pub fn emit_for(
    api: &ApiSpec,
    out: &mut String,
    framework: QueryFramework,
) -> Result<(), std::fmt::Error> {
    let pkg = framework.package();
    let hp = framework.hook_prefix();
    let tp = framework.type_prefix();

    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;
    let has_paginated = api
        .endpoints
        .iter()
        .any(|e| e.method == HttpMethod::Get && is_paginated(e));
    if has_paginated {
        writeln!(
            out,
            "import {{ {hp}Query, {hp}InfiniteQuery, {hp}Mutation, {hp}SuspenseQuery, queryOptions, infiniteQueryOptions }} from '{pkg}';"
        )?;
        writeln!(
            out,
            "import type {{ QueryClient, {tp}QueryOptions, {tp}InfiniteQueryOptions, {tp}MutationOptions }} from '{pkg}';"
        )?;
    } else {
        writeln!(
            out,
            "import {{ {hp}Query, {hp}Mutation, {hp}SuspenseQuery, queryOptions }} from '{pkg}';"
        )?;
        writeln!(
            out,
            "import type {{ QueryClient, {tp}QueryOptions, {tp}MutationOptions }} from '{pkg}';"
        )?;
    }

    // Collect imports
    emit_imports(api, out)?;
    writeln!(out)?;

    for endpoint in &api.endpoints {
        match endpoint.method {
            HttpMethod::Get => emit_query_hook(endpoint, out, framework)?,
            HttpMethod::Post | HttpMethod::Put | HttpMethod::Patch | HttpMethod::Delete => {
                emit_mutation_hook(endpoint, out, framework)?;
            }
        }
        writeln!(out)?;
    }

    Ok(())
}

fn emit_imports(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    let mut type_imports = Vec::new();
    let mut fn_imports = Vec::new();
    let has_any_error = api.endpoints.iter().any(|e| e.error_response.is_some());

    for endpoint in &api.endpoints {
        let id = &endpoint.operation_id;
        let has_path = endpoint
            .parameters
            .iter()
            .any(|p| p.location == ParamLocation::Path);
        let has_query = endpoint
            .parameters
            .iter()
            .any(|p| p.location == ParamLocation::Query);

        if has_path {
            type_imports.push(format!("{id}PathParams"));
        }
        if has_query {
            type_imports.push(format!("{id}QueryParams"));
        }
        if endpoint.response.is_some() && endpoint.response_type == ResponseType::Json {
            type_imports.push(format!("{id}Response"));
        }
        if endpoint.request_body.is_some() {
            type_imports.push(format!("{id}Body"));
        }
        if endpoint.error_response.is_some() {
            type_imports.push(format!("{id}Error"));
        }

        fn_imports.push(id.clone());
    }

    if !type_imports.is_empty() {
        writeln!(
            out,
            "import type {{ {} }} from './types.gen';",
            type_imports.join(", ")
        )?;
    }

    let mut client_type_imports = vec!["RequestConfig"];
    if has_any_error {
        client_type_imports.push("ApiError");
    }
    writeln!(
        out,
        "import type {{ {} }} from './client.gen';",
        client_type_imports.join(", ")
    )?;
    writeln!(
        out,
        "import {{ {} }} from './client.gen';",
        fn_imports.join(", ")
    )?;

    Ok(())
}

fn emit_query_hook(
    endpoint: &Endpoint,
    out: &mut String,
    framework: QueryFramework,
) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let hp = framework.hook_prefix();
    let tp = framework.type_prefix();
    let response_type = match endpoint.response_type {
        ResponseType::Json if endpoint.response.is_some() => format!("{id}Response"),
        ResponseType::Text => "string".to_string(),
        ResponseType::Blob => "Blob".to_string(),
        _ => "void".to_string(),
    };
    let has_path = endpoint
        .parameters
        .iter()
        .any(|p| p.location == ParamLocation::Path);
    let has_query = endpoint
        .parameters
        .iter()
        .any(|p| p.location == ParamLocation::Query);

    // Build params type for the combined hook signature
    let params_type = build_params_type(id, has_path, has_query);
    let has_params = has_path || has_query;

    // Build the client call arguments
    let client_call = build_client_call(id, has_path, has_query);

    // `enabled` pattern: skip query when required path params are undefined
    let needs_enabled = has_path;

    // queryKey function
    if let Some(pt) = &params_type {
        writeln!(out, "export const {id}QueryKey = (params?: {pt}) =>")?;
        writeln!(out, "  ['{id}', ...(params ? [params] : [])] as const;")?;
    } else {
        writeln!(out, "export const {id}QueryKey = () =>")?;
        writeln!(out, "  ['{id}'] as const;")?;
    }
    writeln!(out)?;

    // queryOptions function
    if has_params {
        writeln!(
            out,
            "export const {id}Options = (params?: {}, config?: RequestConfig) =>",
            params_type.as_deref().unwrap()
        )?;
    } else {
        writeln!(
            out,
            "export const {id}Options = (config?: RequestConfig) =>"
        )?;
    }
    writeln!(out, "  queryOptions({{")?;
    if has_params {
        writeln!(out, "    queryKey: {id}QueryKey(params),")?;
        writeln!(out, "    queryFn: () => {client_call},")?;
        if needs_enabled {
            writeln!(out, "    enabled: params !== undefined,")?;
        }
    } else {
        writeln!(out, "    queryKey: {id}QueryKey(),")?;
        writeln!(out, "    queryFn: () => {id}(config),")?;
    }
    writeln!(out, "  }});")?;
    writeln!(out)?;

    // Main query hook
    writeln!(out, "export const {hp}{} = (", capitalize(id))?;
    if has_params {
        writeln!(out, "  params?: {},", params_type.as_deref().unwrap())?;
    }
    writeln!(
        out,
        "  options?: Partial<{tp}QueryOptions<{response_type}>>,"
    )?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    if has_params {
        writeln!(
            out,
            "  {hp}Query({{ ...{id}Options(params, config), ...options }});"
        )?;
    } else {
        writeln!(
            out,
            "  {hp}Query({{ ...{id}Options(config), ...options }});"
        )?;
    }
    writeln!(out)?;

    // Suspense query hook
    writeln!(out, "export const {hp}{}Suspense = (", capitalize(id))?;
    if has_params {
        writeln!(out, "  params?: {},", params_type.as_deref().unwrap())?;
    }
    writeln!(
        out,
        "  options?: Partial<{tp}QueryOptions<{response_type}>>,"
    )?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    if has_params {
        writeln!(
            out,
            "  {hp}SuspenseQuery({{ ...{id}Options(params, config), ...options }});"
        )?;
    } else {
        writeln!(
            out,
            "  {hp}SuspenseQuery({{ ...{id}Options(config), ...options }});"
        )?;
    }
    writeln!(out)?;

    // prefetchQuery helper
    writeln!(out, "export const prefetch{} = (", capitalize(id))?;
    writeln!(out, "  queryClient: QueryClient,")?;
    if has_params {
        writeln!(out, "  params?: {},", params_type.as_deref().unwrap())?;
    }
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    if has_params {
        writeln!(
            out,
            "  queryClient.prefetchQuery({id}Options(params, config));"
        )?;
    } else {
        writeln!(out, "  queryClient.prefetchQuery({id}Options(config));")?;
    }

    // Loader function (framework-agnostic, works with any router)
    writeln!(out)?;
    writeln!(
        out,
        "export const {id}Loader = (queryClient: QueryClient) =>"
    )?;
    if has_params {
        writeln!(out, "  (params: {}) =>", params_type.as_deref().unwrap())?;
        writeln!(out, "    queryClient.ensureQueryData({id}Options(params));")?;
    } else {
        writeln!(out, "  () => queryClient.ensureQueryData({id}Options());")?;
    }

    // Infinite query for paginated endpoints
    if is_paginated(endpoint) {
        writeln!(out)?;
        let page_param = page_param_name(endpoint);
        let is_cursor = page_param == "cursor" || page_param == "after";

        writeln!(out, "export const {hp}{}Infinite = (", capitalize(id))?;
        if has_params {
            writeln!(out, "  params?: {},", params_type.as_deref().unwrap())?;
        }
        if is_cursor {
            writeln!(
                out,
                "  options?: Partial<{tp}InfiniteQueryOptions<{response_type}, Error, {response_type}, {response_type}, unknown[], string | undefined>>,"
            )?;
        } else {
            writeln!(
                out,
                "  options?: Partial<{tp}InfiniteQueryOptions<{response_type}, Error, {response_type}, {response_type}, unknown[], number>>,"
            )?;
        }
        writeln!(out, "  config?: RequestConfig,")?;
        writeln!(out, ") =>")?;
        writeln!(out, "  {hp}InfiniteQuery({{")?;
        writeln!(out, "    queryKey: [...{id}QueryKey(params), 'infinite'],")?;

        // queryFn: merge pageParam into params
        if is_cursor {
            writeln!(
                out,
                "    queryFn: ({{ pageParam }}) => {id}({{ ...params!, {page_param}: pageParam }} as any, config),"
            )?;
            writeln!(
                out,
                "    initialPageParam: undefined as string | undefined,"
            )?;
        } else {
            writeln!(
                out,
                "    queryFn: ({{ pageParam }}) => {id}({{ ...params!, {page_param}: pageParam }} as any, config),"
            )?;
            writeln!(out, "    initialPageParam: 0,")?;
        }

        writeln!(
            out,
            "    getNextPageParam: (lastPage, _allPages, lastPageParam) => {{"
        )?;
        if is_cursor {
            writeln!(
                out,
                "      // Override getNextPageParam based on your API's cursor field"
            )?;
            writeln!(out, "      return undefined;")?;
        } else {
            writeln!(
                out,
                "      if (!Array.isArray(lastPage) || lastPage.length === 0) return undefined;"
            )?;
            writeln!(out, "      return (lastPageParam ?? 0) + lastPage.length;")?;
        }
        writeln!(out, "    }},")?;

        if has_path {
            writeln!(out, "    enabled: params !== undefined,")?;
        }
        writeln!(out, "    ...options,")?;
        writeln!(out, "  }});")?;
    }

    Ok(())
}

fn emit_mutation_hook(
    endpoint: &Endpoint,
    out: &mut String,
    framework: QueryFramework,
) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let has_path = endpoint
        .parameters
        .iter()
        .any(|p| p.location == ParamLocation::Path);
    let has_body = endpoint.request_body.is_some();

    let response_type = match endpoint.response_type {
        ResponseType::Json if endpoint.response.is_some() => format!("{id}Response"),
        ResponseType::Text => "string".to_string(),
        ResponseType::Blob => "Blob".to_string(),
        _ => "void".to_string(),
    };

    let error_type = if endpoint.error_response.is_some() {
        format!("ApiError<{id}Error>")
    } else {
        "Error".to_string()
    };

    // Determine mutation variables type
    let variables_type = match (has_path, has_body) {
        (true, true) => format!("{{ pathParams: {id}PathParams; body: {id}Body }}"),
        (true, false) => format!("{id}PathParams"),
        (false, true) => format!("{id}Body"),
        (false, false) => "void".to_string(),
    };

    // Build mutationFn body
    let mutation_fn = match (has_path, has_body) {
        (true, true) => {
            format!("(vars: {variables_type}) => {id}(vars.pathParams, vars.body, config)")
        }
        (true, false) => format!("(pathParams: {id}PathParams) => {id}(pathParams, config)"),
        (false, true) => format!("(body: {id}Body) => {id}(body, config)"),
        (false, false) => format!("() => {id}(config)"),
    };

    let hp = framework.hook_prefix();
    let tp = framework.type_prefix();

    writeln!(out, "export const {hp}{} = (", capitalize(id))?;
    writeln!(
        out,
        "  options?: {tp}MutationOptions<{response_type}, {error_type}, {variables_type}>,"
    )?;
    writeln!(out, "  config?: RequestConfig,")?;
    writeln!(out, ") =>")?;
    writeln!(out, "  {hp}Mutation({{")?;
    writeln!(out, "    mutationFn: {mutation_fn},")?;
    writeln!(out, "    ...options,")?;
    writeln!(out, "  }});")?;

    Ok(())
}

/// Build a combined params type string for hook signatures.
fn build_params_type(id: &str, has_path: bool, has_query: bool) -> Option<String> {
    match (has_path, has_query) {
        (true, true) => Some(format!("{id}PathParams & {id}QueryParams")),
        (true, false) => Some(format!("{id}PathParams")),
        (false, true) => Some(format!("{id}QueryParams")),
        (false, false) => None,
    }
}

/// Build the client function call, splitting combined params back into separate args.
fn build_client_call(id: &str, has_path: bool, has_query: bool) -> String {
    match (has_path, has_query) {
        (true, true) => format!("{id}(params!, params, config)"),
        (true, false) => format!("{id}(params!, config)"),
        (false, true) => format!("{id}(params, config)"),
        (false, false) => format!("{id}(config)"),
    }
}

/// Detect pagination pattern: endpoint has offset/cursor + limit query params.
fn is_paginated(endpoint: &Endpoint) -> bool {
    let query_names: Vec<&str> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Query)
        .map(|p| p.name.as_str())
        .collect();
    let has_limit = query_names
        .iter()
        .any(|n| *n == "limit" || *n == "pageSize" || *n == "page_size");
    let has_offset = query_names
        .iter()
        .any(|n| *n == "offset" || *n == "cursor" || *n == "page" || *n == "after");
    has_limit && has_offset
}

/// Determine the page param name (offset-based or cursor-based).
fn page_param_name(endpoint: &Endpoint) -> &str {
    let query_names: Vec<&str> = endpoint
        .parameters
        .iter()
        .filter(|p| p.location == ParamLocation::Query)
        .map(|p| p.name.as_str())
        .collect();
    if query_names.contains(&"cursor") {
        return "cursor";
    }
    if query_names.contains(&"after") {
        return "after";
    }
    if query_names.contains(&"page") {
        return "page";
    }
    "offset"
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_uppercase().to_string() + chars.as_str(),
    }
}
