use std::fmt::Write;

use oa_forge_ir::*;

/// Emit MSW v2 request handlers from the API spec.
pub fn emit(api: &ApiSpec, out: &mut String) -> Result<(), std::fmt::Error> {
    writeln!(out, "// Generated by oa-forge. Do not edit.")?;
    writeln!(out)?;
    writeln!(out, "import {{ http, HttpResponse }} from 'msw';")?;
    writeln!(out, "import type * as Types from './types.gen';")?;
    writeln!(out)?;

    // Emit individual handler functions for composability
    for endpoint in &api.endpoints {
        emit_handler_function(endpoint, out)?;
    }

    // Emit default handlers array
    writeln!(out, "export const handlers = [")?;
    for endpoint in &api.endpoints {
        writeln!(out, "  {}Handler(),", endpoint.operation_id)?;
    }
    writeln!(out, "];")?;

    Ok(())
}

/// Emit a factory function for a single endpoint handler.
/// Factory pattern allows users to override the response.
fn emit_handler_function(endpoint: &Endpoint, out: &mut String) -> Result<(), std::fmt::Error> {
    let id = &endpoint.operation_id;
    let method = endpoint.method.as_lower();
    let msw_path = path_to_colon_params(&endpoint.path);

    let has_response = endpoint.response.is_some();
    let response_type = if has_response {
        format!("Types.{id}Response")
    } else {
        "undefined".to_string()
    };

    // Factory function signature
    writeln!(
        out,
        "export function {id}Handler(override?: {response_type} | (() => {response_type})) {{"
    )?;

    writeln!(out, "  return http.{method}('{msw_path}', () => {{")?;

    // Generate response based on response type
    match endpoint.response_type {
        ResponseType::Void => {
            writeln!(out, "    return new HttpResponse(null, {{ status: 204 }});")?;
        }
        ResponseType::Text => {
            writeln!(
                out,
                "    const data = typeof override === 'function' ? override() : override;"
            )?;
            writeln!(out, "    return HttpResponse.text(data as string ?? '');")?;
        }
        ResponseType::Blob => {
            writeln!(out, "    return new HttpResponse(null, {{ status: 200 }});")?;
        }
        ResponseType::Json => {
            writeln!(
                out,
                "    const data = typeof override === 'function' ? override() : override;"
            )?;
            writeln!(out, "    return HttpResponse.json(data ?? {{}});")?;
        }
    }

    writeln!(out, "  }});")?;
    writeln!(out, "}}")?;
    writeln!(out)?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn converts_openapi_path_to_msw() {
        assert_eq!(path_to_colon_params("/pets"), "/pets");
        assert_eq!(path_to_colon_params("/pets/{petId}"), "/pets/:petId");
        assert_eq!(
            path_to_colon_params("/users/{userId}/posts/{postId}"),
            "/users/:userId/posts/:postId"
        );
    }
}
